### PR TITLE
Added Sample tests for Group SSR based on group.spec.js

### PR DESCRIPTION
**Pull request by tjmonsi**
Hey...

I had fun trying out this one. Anyway, I couldn't test if the Group routing works because SSR doesn't have a FlowRouter.go mechanism. I'll try to research on how to do a hack on how to test that. But if you have any ideas, I can put it up here

### CODE REVIEW

**Comment by arunoda** [comment]
This is great. You need to lint your code. 
Check here: https://github.com/kadirahq/flow-router/blob/ssr/CONTRIBUTING.md#tests

**Comment by arunoda** [comment]
One thing, it seems like we don't have any server side functionality for groups yet. Just like triggers. Actually we need to test them.

I fear these tests are somehow implemented here. See: https://github.com/kadirahq/flow-router/blob/ssr/test/common/group.spec.js

I so, write tests for the group in `lib/group.js` and put test inside that directory. You may can merge the tests you've written as well, if needed.

**Comment by tjmonsi** [comment]
Would that be in conflict on Group server and client?

**Comment by tjmonsi** [comment]
I changed the Group tests into BDD specs + linted. Learning a lot! :smile:

**Comment by tjmonsi** [comment]
There are 3 failures to be exact: 

The 3 test cases in the original group.spec.js (which are also here) would not work in the Server because of the missing Router.go functionality on the server side

**Comment by arunoda** [comment]
Okay. In this case, try to add a dummy .go functionality in the router. It
should do nothing.

**Comment by tjmonsi** [comment]
Actually in the `/lib/router.js`, the SharedRouter already have a function
`go()` the does nothing. The implementation of `go()` is in the
`/client/router.js` and it uses the page.js to change the page. We don't
have yet the SSR version of page.js to be able to be able to change the
path and have an effect in calling the action function in the Group's route.

**Comment by tjmonsi** [comment]
I am not yet familiar on how calling Router.go will be able to call the action method in a certain route. I'm studying it right now so to try to mimic it on the server side. Maybe I can create a Router.go on the server if I can answer that... unless Router.go is not needed on SSR

**Comment by arunoda** [comment]
Okay. If so, simply run tests on the client.
For the guard code within a "if(Meteor.isClient)" block.

**Comment by tjmonsi** [comment]
Just did and currently pushing.

**Comment by tjmonsi** [comment]
Test complete.

**Comment by arunoda** [comment]
Awesome.

**Comment by tjmonsi** [comment]
Ok will work on other tests making it into BDD and putting it on either lib
or client for now

**Comment by arunoda** [comment]
That's awesome.

**Pull request merged**
