### PR TITLE
Ssr shared server client code

### PR DESCRIPTION
**Pull request by elie222**

### CODE REVIEW

**Comment by elie222** [comment]
Tests are failing now but I have no idea why. It looks like the comparison passed.

**Comment by elie222** [comment]
finished first stage of refactoring all the files. there are tests that are failing and i don't understand why

**Comment by arunoda** [comment]
Hey, send this PR to the `ssr` branch.

**Comment by arunoda** [comment]
Also, rebase your changes from the current `ssr` branch.

**Comment by elie222** [comment]
Will do tomorrow

**Comment by arunoda** [comment]
Great!

**Pull request closed without merging**
