### PR TITLE
Removed cosmos:browserify, replaced with modules for new meteor 1.3 support. #552

### PR DESCRIPTION
**Pull request by markoshust**
Breaking change for meteor 1.2. 

https://github.com/kadirahq/flow-router/issues/552

### CODE REVIEW

**Comment by arunoda** [comment]
Can I use this even with Meteor 1.2 apps?

**Comment by markoshust** [comment]
I don't think so -- pretty sure `modules` package is specific to 1.3. So this would be a breaking update to 1.2.

**Comment by arunoda** [comment]
I think what we can do about this. May be we can quick the launch of 4.0

**Comment by arunoda** [comment]
I'll remove browserify from the 3.x versions.

**Comment by markoshust** [comment]
@arunoda thanks. are there any/many breaking changes from going to flow router 2.0 to 3.0? i wasn't sure how stable 3.0 was also.

**Comment by arunoda** [comment]
There's no breaking changes other than route level subscriptions.

**Comment by tmeasday** [comment]
@arunoda is it possible to release a beta version of 3.0? That way people can upgrade apps to 1.3 now and continue to use FR..

**Comment by arunoda** [comment]
@tmeasday Will do it.

**Comment by arunoda** [comment]
@tmeasday I started migrating here: https://github.com/kadirahq/flow-router/tree/use-meteor-modules-support

But I'm getting this error: https://gist.github.com/arunoda/022e27ac755acb60ff34

May be I need to do something on package versions.
Looking for some help to figure this out.

@markoshust How did you get this to working?

**Comment by markoshust** [comment]
@arunoda I cloned this repo to packages/flow-router, then made the updates in https://github.com/markoshust/flow-router/commit/1fe58d605039c46c3620d1981136fef3397cda82

**Comment by tmeasday** [comment]
@arunoda I'm not sure, this package.json is kind of weird in that it doesn't `api.use()` the actual package in the `onTest` block. The error doesn't make a lot of sense to me to be honest. 

Have you tried just `meteor run`-ing it?

**Comment by arunoda** [comment]
@tmeasday We use a common function a specific packages and use them on tests. I think I need to add the --release flag when running tests.

**Comment by arunoda** [comment]
Let's discuss this on here - https://github.com/kadirahq/flow-router/issues/552

**Comment by aaronjudd** [comment]
@arunoda is this actually resolved, now that 1.3 is out, client-browserify still produces issues.

**Pull request closed without merging**
