### PR TITLE
Support for ignoring paths

### LINKED ISSUE #387: Router for serving static files
A followup to #235, because it is locked.

I think the current approaches to make links to server-side files is very limited. It is really hard to dynamically make sure that links have `ref` or some other attribute when links are supplied by the user. In our case, we have a rich-text editor where user can supply a link. Now, that link can be to an external page, to internal page, or to server-side file. Now with current approach we would have to parse all links and change how they are rendered just so that we can add necessary attribute. It would be much easier if we could say that for example, everything under `/uploads/` should not be processed by flow-router/page.js. This is then configured in one place, near routes, instead of having this all around the place.

It would be also cool if this could be enabled automatically for all client-side assets and files in app's `/public/` directory.

### PR DESCRIPTION
**Pull request by mitar**
Fixes #387.

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks for the PR.
We've hacked page.js in many ways. I don't like to add more hacks to it.
And current page.js's ignore path API looks very nice and adequate for all apps.

But we can add a good entry in the README.

**Comment by mitar** [comment]
> And current page.js's ignore path API looks very nice and adequate for all apps.

Hm, definitely not for all apps. Like, what would be a good pattern to say that all links under `/uploads` should be ignored by page.js? I do not think it can be any nicer than [this](https://github.com/mitar/council-app/blob/master/packages/storage/lib.coffee#L9).

**Comment by arunoda** [comment]
But adding a HTML tag is not that hard.

**Comment by mitar** [comment]
In all links which can potentially be rendered on the site? So now when I have a HTML rich-text editor I have to parse the HTML, check all the links, check if any of the links are pointing to `/uploads` directory, modify the link and add a HTML attribute, and then hope this will not confuse the rich-text editor next time I will open it up again to continue editing?

**Comment by arunoda** [comment]
So it's still doable.
Sorry I'm not going to take this PR.
But I like to add the docs to README.

**Comment by mitar** [comment]
Sorry, I need this feature. I created a fork: https://atmospherejs.com/peerlibrary/flow-router

**Comment by mitar** [comment]
Documentation: https://github.com/peerlibrary/flow-router/#ignoring-links

**Comment by sahanDissanayake** [comment]
did this happen ? 

My scenario is that I wanna serve a stATIC JS file from S3 when a user hit http://example.com/embed.js

With the latest Flowrouter is this doable ?

**Comment by sahanDissanayake** [comment]
should i just use https://github.com/meteorhacks/picker ?

**Comment by mitar** [comment]
No. I have a fork above.

**Pull request closed without merging**
