### PR TITLE
Fix #314

### LINKED ISSUE #314: Redirect to sub-route in same group does not trigger reactive update of .getRouteName()
Scenario:

I have set up a group route containing a teaser page at /group and a hidden page at /group/page. The idea is to show the teaser page if the user is not logged in, and replace it by the hidden page the user has logged in. Here is my route configuration for this:

```js
var myGroupRoutes = FlowRouter.group({
  prefix: '/group'
});

myGroupRoutes.route('/', {
  // If user is logged in, redirect to sub page
  triggersEnter: [function (context, redirect) {
    if (Meteor.user()) {
      redirect('myGroupPage');
    }
  }],
  // If user is not logged in, show teaser page
  action: function () {
    BlazeLayout.render('layout', {
      mainCanvas: 'teaserPage'
    });
  },
  name: 'myGroup'
});

myGroupRoutes.route('/page', {
  // If user is not logged in, redirect to teaser page
  triggersEnter: [function (context, redirect) {
    if (!Meteor.user()) {
      redirect('myGroup');
    }
  }],
  action: function () {
    BlazeLayout.render('layout', {
      mainCanvas: 'subPage'
    });
  },
  name: 'myGroupPage'
});
```
I am also using a navigation bar with two nav items: one for the app home (called root, with route path /) and a second item for the group route, which shall be highlighted for for both /group and /group/page. I am using  ```zimme:meteor-activeroute``` to do this, with this configuration:
```html
<li class="{{isActiveRoute 'root'}}"><a href="{{pathFor 'root'}}">Home</a></li>
<li class="{{isActiveRoute regex='^myGroup'}}"><a href="{{pathFor 'myGroup'}}">Menu Entry</a></li>
```
The switch between the nav items works fine if the user is not logged in. However, once the user is logged in, clicking on the second nav item will not cause a switch of the nav item highlight (i.e. the isActiveRoute helpers won't update). After debugging and writing FlowRouter's route state to the console, I found out that FlowRouter's reactive functions like .getRouteName() won't reactively update if a redirect to a sub-route of a route group takes place. The reactive updates only work if the redirect target is the root of the route group. I tested this by placing a dummy helper in my template that just reports .getRouteName() to the console.

### PR DESCRIPTION
**Pull request by mbernath**

### CODE REVIEW

**Comment by arunoda** [comment]
Could you also write a test case specific to this case? 
Then we are good to go.

**Comment by mbernath** [comment]
Here you go. I extended the existing test case. Seemed more appropriate because it just passed ``null`` as context.

**Comment by arunoda** [comment]
Hey, I fixed #314 in a different way. I tested and do some work on this and found out, this is not the best approach.
Here, it also fire event even if on the triggers. For an example, if the routeA trigger redirects a user to routeB, routeA should not should not be consider as a route change.
Only routeB.

This PR marks both as a route change. Here's how I did this.
See: https://github.com/kadirahq/flow-router/commit/dbed310c8fb53f90acff1cb77253def1f82bf820

**Comment by arunoda** [comment]
So, I'm gonna close this PR. 
Thanks for working on this.

**Pull request closed without merging**
