### PR TITLE
added group for route on server and moved some client group tests to common tests

### PR DESCRIPTION
**Pull request by elie222**
If you could take a look at this. I'm not certain what I did was right

### CODE REVIEW

**Comment by arunoda** [comment]
This seems pretty legit to me. You simply change move the group assignment to shared classes.
Is there anymore to this?

**Comment by elie222** [comment]
We were missing group functionality for server in places. I wasn't sure if
that was intentional or not

**Comment by arunoda** [comment]
That's not intentional.

**Comment by arunoda** [comment]
Shall I take this or do you have some other stuffs to do?

**Comment by elie222** [comment]
I'll keep working on finding common tests but this is good to take as is

**Comment by arunoda** [comment]
Okay. Let's do like this. Try to find common tests and move it to this PR. Once you feel that's good, drop me a message.

BTW: Try changing the title.
Also create a new branch for every PR.

**Comment by elie222** [comment]
i made a new pull request from another branch. i found all client tests that can be moved to common. closing this pull request now

**Pull request closed without merging**
